kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-backup
  labels:
    app: kube-backup
    env: system
rules:
# More restricted permissions always seem to block 'exec'
#  - apiGroups: ["*"]
#    resources: ["pods"]
#    verbs: ["*"]
#    verbs: ["get","list","proxy"]
#  - apiGroups: ["*"]
#    resources: ["secrets"]
#    verbs: ["get"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-backup
  labels:
    app: kube-backup
    env: system
subjects:
  - kind: ServiceAccount
    namespace: kube-backup
    name: default
  - kind: User
    name: kube-backup
roleRef:
  kind: ClusterRole
  name: kube-backup
  apiGroup: rbac.authorization.k8s.io
